[package]
name = "boa-wasm"
version = "0.1.0"
authors = ["hpp2334 <hpp2334@outlook.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
boa_engine = { git = "https://github.com/boa-dev/boa.git", rev = "2c1eb630fd698d71b164194be4fef95ce9477fec", features = ["js"] }
wasm-bindgen = "0.2.84"
console_error_panic_hook = { version = "0.1.7" }
swc_core = { version = "45.0.2", features = [
  "ecma_ast_serde",
  "ecma_codegen",
  "binding_macro_wasm",
  "ecma_transforms",
  "ecma_visit",
  "ecma_helpers_inline",
]}
getrandom = { version = "0.3.4", features = ["wasm_js"] }
serde = { version = "1.0", features = ["derive"]}
serde-wasm-bindgen = "0.6.5"
icu_normalizer = "2.1.1"

[profile.release]
debug = true